name = "trendsongs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://trendsongbe-production.up.railway.app"
NEXT_PUBLIC_SITE_URL = "https://trend-songs.com"
NODE_VERSION = "22"
