name = "trendsongs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://trendsongbe-production.up.railway.app"
NEXT_PUBLIC_SITE_URL = "https://trend-songs.com"
NEXT_PUBLIC_ADMIN_API_KEY = "6e1ffe903ede4de8d3235a461ac98455785bc21873053c9d06f6a068ae472858"
NODE_VERSION = "22"
